inventario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('productos.urls', 'products'), namespace='products')),
    
]

productos/urls.py
from django.urls import path
from .views import order_views, product_views, containers_views, views

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),  # Página principal (Dashboard)

    path('product/', product_views.ProductListView.as_view(), name='product_list'),
    path('product/new/', product_views.ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/edit/', product_views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', product_views.ProductDeleteView.as_view(), name='product_delete'),

    path('containers/', containers_views.ContainerListView.as_view(), name='container_list'),
    path('container/new/', containers_views.ContainerCreateView.as_view(), name='container_create'),
    path('container/<int:pk>/edit/', containers_views.ContainerUpdateView.as_view(), name='container_update'),
    path('container/<int:pk>/delete/', containers_views.ContainerDeleteView.as_view(), name='container_delete'),

    path('orders/', order_views.OrderListView.as_view(), name='order_list'),
    path('orders/new/', order_views.OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/edit/', order_views.OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', order_views.OrderDeleteView.as_view(), name='order_delete'),
]

productos/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .models import Product, Container
from .forms import ProductForm, ContainerForm

# View to list products
class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Productos'
        context['create_url'] = reverse('products:product_create')
        return context

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            products = [product.to_json() for product in Product.objects.all()]
            return JsonResponse({'data': products})
        except Exception as e:
            print("Error en vista ProductListView:", e)
            return JsonResponse({'error': str(e)}, status=500)

# View to create a new product
class ProductCreateView(SuccessMessageMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_form.html'
    success_url = reverse_lazy('products:product_list')
    success_message = "Product created successfully"


# View to update an existing product
class ProductUpdateView(SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_form.html'
    success_url = reverse_lazy('products:product_list')
    success_message = "Product updated successfully"


# View to delete a product
class ProductDeleteView(SuccessMessageMixin, DeleteView):
    model = Product
    template_name = 'products/product_confirm_delete.html'
    success_url = reverse_lazy('products:product_list')
    success_message = "Product deleted successfully"


# View to list containers
class ContainerListView(SuccessMessageMixin, ListView):
    model = Container
    template_name = 'products/container_list.html'
    context_object_name = 'containers'


# View to create a new container
class ContainerCreateView(CreateView):
    model = Container
    form_class = ContainerForm
    template_name = 'products/container_form.html'
    success_url = reverse_lazy('products:container_list')
    success_message = "Container created successfully"

    def form_valid(self, form):
        try:
            self.object = form.save()
            messages.success(self.request, self.success_message)
            return super().form_valid(form)
        except IntegrityError as e:
            messages.error(self.request, f"An error occurred while saving the container: {str(e)}")
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was a problem with the form. Please check the fields.")
        return super().form_invalid(form)


# View to update an existing container
class ContainerUpdateView(SuccessMessageMixin, UpdateView):
    model = Container
    form_class = ContainerForm
    template_name = 'products/container_form.html'
    success_url = reverse_lazy('products:container_list')
    success_message = "Container updated successfully"


# View to delete a container
class ContainerDeleteView(SuccessMessageMixin, DeleteView):
    model = Container
    template_name = 'products/container_confirm_delete.html'
    success_url = reverse_lazy('products:container_list')
    success_message = "Container deleted successfully"

productos/views/containers_views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from ..models import Product, Container
from ..forms import ProductForm, ContainerForm

# View to list containers
class ContainerListView(SuccessMessageMixin, ListView):
    model = Container
    template_name = 'containers/container_list.html'
    context_object_name = 'containers'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Envases'
        context['create_url'] = reverse('products:container_create')  # Asegúrate de tener esta URL
        return context

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            containers = [container.to_json() for container in Container.objects.all()]
            return JsonResponse({'data': containers})
        except Exception as e:
            print("Error en vista ContainerListView:", e)
            return JsonResponse({'error': str(e)}, status=500)

# View to create a new container
class ContainerCreateView(CreateView):
    model = Container
    form_class = ContainerForm
    template_name = 'containers/container_form.html'
    success_url = reverse_lazy('products:container_list')
    success_message = "Container created successfully"

    def form_valid(self, form):
        try:
            self.object = form.save()
            messages.success(self.request, self.success_message)
            return super().form_valid(form)
        except IntegrityError as e:
            messages.error(self.request, f"An error occurred while saving the container: {str(e)}")
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was a problem with the form. Please check the fields.")
        return super().form_invalid(form)


# View to update an existing container
class ContainerUpdateView(SuccessMessageMixin, UpdateView):
    model = Container
    form_class = ContainerForm
    template_name = 'containers/container_form.html'
    success_url = reverse_lazy('products:container_list')
    success_message = "Container updated successfully"


# View to delete a container
class ContainerDeleteView(SuccessMessageMixin, DeleteView):
    model = Container
    template_name = 'containers/container_confirm_delete.html'
    success_url = reverse_lazy('products:container_list')
    success_message = "Container deleted successfully"

productos/views/order_views.py
# orders/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse, HttpResponseNotAllowed
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from ..models import Order
from ..forms import OrderForm, OrderDetailFormSet


# View to list orders
class OrderListView(ListView):
    model = Order
    template_name = 'orders/order_list.html'
    context_object_name = 'orders'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Order List'
        context['create_url'] = reverse('products:order_create')
        return context

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            orders = [order.to_json() for order in Order.objects.all()]
            return JsonResponse({'data': orders})
        except Exception as e:
            print("Error in OrderListView:", e)
            return JsonResponse({'error': str(e)}, status=500)


# View to create a new order
class OrderCreateView(SuccessMessageMixin, CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'orders/order_form.html'
    success_url = reverse_lazy('products:order_list')
    success_message = "Order created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = OrderDetailFormSet(self.request.POST)
        else:
            context['formset'] = OrderDetailFormSet()
        context['title'] = 'New Order'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        try:
            if form.is_valid() and formset.is_valid():
                self.object = form.save()
                formset.instance = self.object
                formset.save()
                messages.success(self.request, self.success_message)
                return super().form_valid(form)
            else:
                return self.form_invalid(form)
        except IntegrityError as e:
            form.add_error(None, f"Database Error: {e}")
            return self.form_invalid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class OrderUpdateView(SuccessMessageMixin, UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'orders/order_form.html'
    success_url = reverse_lazy('products:order_list')
    success_message = "Order updated successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = OrderDetailFormSet(self.request.POST, instance=self.object)
        else:
            context['formset'] = OrderDetailFormSet(instance=self.object)
        context['title'] = 'Edit Order'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        try:
            if form.is_valid() and formset.is_valid():
                self.object = form.save()
                formset.instance = self.object
                formset.save()
                messages.success(self.request, self.success_message)
                return super().form_valid(form)
            else:
                return self.form_invalid(form)
        except IntegrityError as e:
            form.add_error(None, f"Database Error: {e}")
            return self.form_invalid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class OrderDeleteView(SuccessMessageMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('products:order_list')
    success_message = "Order deleted successfully"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'message': self.success_message})
        return redirect(self.success_url)

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

productos/views/product_views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from ..models import Product, Container
from ..forms import ProductForm, ContainerForm

# View to list products
class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Productos'
        context['create_url'] = reverse('products:product_create')
        return context

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            products = [product.to_json() for product in Product.objects.all()]
            return JsonResponse({'data': products})
        except Exception as e:
            print("Error en vista ProductListView:", e)
            return JsonResponse({'error': str(e)}, status=500)

# View to create a new product
class ProductCreateView(SuccessMessageMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_form.html'
    success_url = reverse_lazy('products:product_list')
    success_message = "Product created successfully"


# View to update an existing product
class ProductUpdateView(SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_form.html'
    success_url = reverse_lazy('products:product_list')
    success_message = "Product updated successfully"


# View to delete a product
class ProductDeleteView(SuccessMessageMixin, DeleteView):
    model = Product
    template_name = 'products/product_confirm_delete.html'
    success_url = reverse_lazy('products:product_list')
    success_message = "Product deleted successfully"

productos/views/views.py
# views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

productos/templates/containers/container_form.html
{% extends 'base_generic.html' %}

{% block title %}Container Form{% endblock %}

{% block content %}
  <h2>{% if form.instance.pk %}Edit{% else %}New{% endif %} Container</h2>

  <!-- Global messages block (success or error) -->
  <!--
  {% if messages %}
    <div class="alert-container">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    </div>
  {% endif %}
  -->

  <form method="post">
    {% csrf_token %}
    
    <!-- Render fields manually with validation errors -->
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
          <div class="alert alert-danger mt-2">
            {% for error in field.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    {% endfor %}
  
    <button type="submit" class="btn btn-primary">Save</button>
  </form>

{% endblock %}

productos/templates/containers/container_list.html
{% extends 'list.html' %}
{% load static %}

{% block title %}Listado de Envases{% endblock %}

{% block table_headers %}
    <th>ID</th>
    <th>Nombre</th>
    <th>Peso</th>
    <th>Fecha de Creación</th>
    <th>Acciones</th>
{% endblock %}

{% block table_body %}
<!-- Se llenará automáticamente con AJAX -->
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            processing: true,
            serverSide: false,  // Usa true si implementas paginación en servidor
            ajax: {
                url: "{% url 'products:container_list' %}",
                type: "POST",
                headers: {
                    'X-CSRFToken': getCookie('csrftoken')
                },
                dataSrc: "data",  // Mapea la respuesta de AJAX al formato esperado
                error: function(xhr, error, thrown) {
                    console.log("Error en AJAX: ", xhr.responseText);
                }
            },
            columns: [
                { data: "id" },  // Columna para el nombre del contenedor
                { data: "name" },  // Columna para el nombre del contenedor
                { 
                    data: "weight", 
                    render: function(data) {
                        return data + " g";  // Formatea el peso con "g" al final
                    }
                },
                { 
                    data: "created_at", 
                    render: function(data) {
                        return new Date(data).toLocaleString();  // Formatea la fecha en formato legible
                    }
                },
                { 
                    data: "id", 
                    render: function(data, type, row) {
                        const edit_url = "{% url 'products:container_update' '0' %}".replace('0', data);
                        const delete_url = "{% url 'products:container_delete' '0' %}".replace('0', data);
                        return `
                            <a href="${edit_url}" class="btn btn-warning btn-sm">Editar</a>
                            <a href="${delete_url}" class="btn btn-danger btn-sm">Eliminar</a>
                        `;
                    }, 
                    orderable: false, 
                    searchable: false 
                }
            ],
            language: {
                url: "https://cdn.datatables.net/plug-ins/1.13.6/i18n/es-ES.json"
            }
        });
    });

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
{% endblock %}